"""Add OlfactoryDNA and ScentPhenotype models

Revision ID: 6db79ba09ed3
Revises: 001_initial_schema
Create Date: 2025-10-01 14:23:29.907648+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '6db79ba09ed3'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create OlfactoryDNA table
    op.create_table('olfactory_dna',
    sa.Column('dna_id', sa.String(), nullable=False),
    sa.Column('lineage', sa.JSON(), nullable=False),
    sa.Column('genotype', sa.JSON(), nullable=False),
    sa.Column('story', sa.Text(), nullable=False),
    sa.Column('dna_signature', sa.String(length=200), nullable=True),
    sa.Column('complexity_level', sa.Integer(), nullable=True),
    sa.Column('innovation_score', sa.Float(), nullable=True),
    sa.Column('creator_id', sa.String(length=100), nullable=True),
    sa.Column('creation_method', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_validated', sa.Boolean(), nullable=True),
    sa.Column('validation_scores', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('complexity_level >= 1 AND complexity_level <= 10', name='check_dna_complexity'),
    sa.CheckConstraint('innovation_score >= 0 AND innovation_score <= 10', name='check_dna_innovation'),
    sa.PrimaryKeyConstraint('dna_id')
    )
    op.create_index('ix_olfactory_dna_creation_method', 'olfactory_dna', ['creation_method'], unique=False)
    op.create_index('ix_olfactory_dna_creator', 'olfactory_dna', ['creator_id'], unique=False)
    op.create_index('ix_olfactory_dna_signature', 'olfactory_dna', ['dna_signature'], unique=False)

    # Create ScentPhenotype table
    op.create_table('scent_phenotypes',
    sa.Column('phenotype_id', sa.String(), nullable=False),
    sa.Column('based_on_dna', sa.String(), nullable=False),
    sa.Column('epigenetic_trigger', sa.JSON(), nullable=False),
    sa.Column('recipe', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('phenotype_name', sa.String(length=200), nullable=True),
    sa.Column('phenotype_code', sa.String(length=100), nullable=True),
    sa.Column('variant_type', sa.String(length=50), nullable=True),
    sa.Column('market_performance', sa.JSON(), nullable=True),
    sa.Column('customer_rating', sa.Float(), nullable=True),
    sa.Column('expert_score', sa.Float(), nullable=True),
    sa.Column('production_status', sa.String(length=50), nullable=True),
    sa.Column('batch_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("production_status IN ('concept', 'prototype', 'production', 'discontinued')", name='check_phenotype_status'),
    sa.CheckConstraint("variant_type IN ('original', 'seasonal', 'limited', 'custom')", name='check_phenotype_variant'),
    sa.CheckConstraint('customer_rating >= 0 AND customer_rating <= 5', name='check_phenotype_rating'),
    sa.CheckConstraint('expert_score >= 0 AND expert_score <= 10', name='check_phenotype_expert_score'),
    sa.ForeignKeyConstraint(['based_on_dna'], ['olfactory_dna.dna_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('phenotype_id'),
    sa.UniqueConstraint('phenotype_code')
    )
    op.create_index('ix_scent_phenotypes_code', 'scent_phenotypes', ['phenotype_code'], unique=False)
    op.create_index('ix_scent_phenotypes_dna', 'scent_phenotypes', ['based_on_dna'], unique=False)
    op.create_index('ix_scent_phenotypes_status', 'scent_phenotypes', ['production_status'], unique=False)
    op.create_index('ix_scent_phenotypes_variant', 'scent_phenotypes', ['variant_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop ScentPhenotype indexes and table
    op.drop_index('ix_scent_phenotypes_variant', table_name='scent_phenotypes')
    op.drop_index('ix_scent_phenotypes_status', table_name='scent_phenotypes')
    op.drop_index('ix_scent_phenotypes_dna', table_name='scent_phenotypes')
    op.drop_index('ix_scent_phenotypes_code', table_name='scent_phenotypes')
    op.drop_table('scent_phenotypes')

    # Drop OlfactoryDNA indexes and table
    op.drop_index('ix_olfactory_dna_signature', table_name='olfactory_dna')
    op.drop_index('ix_olfactory_dna_creator', table_name='olfactory_dna')
    op.drop_index('ix_olfactory_dna_creation_method', table_name='olfactory_dna')
    op.create_table('fragrance_ingredients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('english_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('korean_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('fragrance_family', sa.VARCHAR(length=100), nullable=True),
    sa.Column('note_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('origin', sa.VARCHAR(length=255), nullable=True),
    sa.Column('cas_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('intensity', sa.FLOAT(), nullable=True),
    sa.Column('longevity', sa.FLOAT(), nullable=True),
    sa.Column('sillage', sa.FLOAT(), nullable=True),
    sa.Column('price_range', sa.VARCHAR(length=50), nullable=True),
    sa.Column('safety_rating', sa.VARCHAR(length=10), nullable=True),
    sa.Column('allergen_info', sa.TEXT(), nullable=True),
    sa.Column('blending_guidelines', sa.TEXT(), nullable=True),
    sa.Column('supplier_info', sa.TEXT(), nullable=True),
    sa.Column('molecular_formula', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cas_number'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_fragrance_ingredients_note_type', 'fragrance_ingredients', ['note_type'], unique=False)
    op.create_index('ix_fragrance_ingredients_name', 'fragrance_ingredients', ['name'], unique=False)
    op.create_index('ix_fragrance_ingredients_id', 'fragrance_ingredients', ['id'], unique=False)
    op.create_index('ix_fragrance_ingredients_fragrance_family', 'fragrance_ingredients', ['fragrance_family'], unique=False)
    op.create_index('ix_fragrance_ingredients_category', 'fragrance_ingredients', ['category'], unique=False)
    op.create_table('fragrance_recipes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('fragrance_family', sa.VARCHAR(length=100), nullable=True),
    sa.Column('mood', sa.VARCHAR(length=255), nullable=True),
    sa.Column('season', sa.VARCHAR(length=100), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=50), nullable=True),
    sa.Column('intensity', sa.VARCHAR(length=50), nullable=True),
    sa.Column('longevity', sa.VARCHAR(length=50), nullable=True),
    sa.Column('sillage', sa.VARCHAR(length=50), nullable=True),
    sa.Column('recipe_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('total_percentage', sa.FLOAT(), nullable=True),
    sa.Column('notes', sqlite.JSON(), nullable=True),
    sa.Column('instructions', sa.TEXT(), nullable=True),
    sa.Column('story', sa.TEXT(), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('quality_score', sa.FLOAT(), nullable=True),
    sa.Column('complexity_score', sa.FLOAT(), nullable=True),
    sa.Column('creativity_score', sa.FLOAT(), nullable=True),
    sa.Column('feasibility_score', sa.FLOAT(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fragrance_recipes_name', 'fragrance_recipes', ['name'], unique=False)
    op.create_index('ix_fragrance_recipes_id', 'fragrance_recipes', ['id'], unique=False)
    op.create_index('ix_fragrance_recipes_fragrance_family', 'fragrance_recipes', ['fragrance_family'], unique=False)
    op.drop_index('ix_scent_phenotypes_variant', table_name='scent_phenotypes')
    op.drop_index('ix_scent_phenotypes_status', table_name='scent_phenotypes')
    op.drop_index('ix_scent_phenotypes_dna', table_name='scent_phenotypes')
    op.drop_index('ix_scent_phenotypes_code', table_name='scent_phenotypes')
    op.drop_table('scent_phenotypes')
    op.drop_index('ix_generated_recipes_user', table_name='generated_recipes')
    op.drop_index('ix_generated_recipes_timestamp', table_name='generated_recipes')
    op.drop_index(op.f('ix_generated_recipes_conversation_id'), table_name='generated_recipes')
    op.drop_index('ix_generated_recipes_conversation', table_name='generated_recipes')
    op.drop_table('generated_recipes')
    op.drop_index('ix_olfactory_dna_signature', table_name='olfactory_dna')
    op.drop_index('ix_olfactory_dna_creator', table_name='olfactory_dna')
    op.drop_index('ix_olfactory_dna_creation_method', table_name='olfactory_dna')
    op.drop_table('olfactory_dna')
    # ### end Alembic commands ###