# Promtail Configuration
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # ==========================================================================
  # Fragrance AI Application Logs (JSON)
  # ==========================================================================
  - job_name: fragrance-ai-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: fragrance-ai
          app: fragrance-ai-api
          __path__: /app/logs/*.log

    pipeline_stages:
      # Parse JSON logs
      - json:
          expressions:
            timestamp: timestamp
            level: level
            logger: logger
            message: message
            component: component
            log_type: log_type
            # LLM fields
            mode: mode
            qwen_ok: qwen_ok
            mistral_fix: mistral_fix
            hints: hints
            elapsed_ms: elapsed_ms
            # RL fields
            algo: algo
            loss: loss
            reward: reward
            entropy: entropy
            clip_frac: clip_frac
            # API fields
            method: method
            endpoint: endpoint
            status_code: status_code
            latency_ms: latency_ms

      # Extract timestamp
      - timestamp:
          source: timestamp
          format: RFC3339Nano

      # Add labels for filtering
      - labels:
          level:
          component:
          log_type:
          mode:
          algo:

      # Drop debug logs in production (optional)
      # - match:
      #     selector: '{level="DEBUG"}'
      #     action: drop

  # ==========================================================================
  # Docker Container Logs
  # ==========================================================================
  - job_name: docker-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'

    pipeline_stages:
      # Try to parse as JSON
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
          # Ignore errors if not JSON
          source: message

      # Extract timestamp if present
      - timestamp:
          source: timestamp
          format: RFC3339Nano
          # Fallback to current time if not present
          action_on_failure: fudge

      # Add container labels
      - labels:
          container:
          stream:

  # ==========================================================================
  # System Logs (Linux)
  # ==========================================================================
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/syslog

    pipeline_stages:
      # Parse syslog format
      - regex:
          expression: '^(?P<timestamp>\S+\s+\S+\s+\S+) (?P<hostname>\S+) (?P<service>\S+)\[(?P<pid>\d+)\]: (?P<message>.*)$'

      # Extract timestamp
      - timestamp:
          source: timestamp
          format: Jan 2 15:04:05

      # Add labels
      - labels:
          hostname:
          service:

  # ==========================================================================
  # Application-Specific Logs
  # ==========================================================================
  - job_name: fragrance-ai-llm
    static_configs:
      - targets:
          - localhost
        labels:
          job: fragrance-ai
          component: LLM
          __path__: /app/logs/llm*.log

    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            mode: mode
            qwen_ok: qwen_ok
            mistral_fix: mistral_fix
            hints: hints
            elapsed_ms: elapsed_ms
            cache_hit: cache_hit

      - timestamp:
          source: timestamp
          format: RFC3339Nano

      - labels:
          level:
          mode:

  - job_name: fragrance-ai-rl
    static_configs:
      - targets:
          - localhost
        labels:
          job: fragrance-ai
          component: RL
          __path__: /app/logs/rl*.log

    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            algo: algo
            loss: loss
            reward: reward
            entropy: entropy
            clip_frac: clip_frac

      - timestamp:
          source: timestamp
          format: RFC3339Nano

      - labels:
          level:
          algo:

  - job_name: fragrance-ai-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: fragrance-ai
          component: API
          __path__: /app/logs/api*.log

    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            method: method
            endpoint: endpoint
            status_code: status_code
            latency_ms: latency_ms

      - timestamp:
          source: timestamp
          format: RFC3339Nano

      - labels:
          level:
          method:
          endpoint:
