#!/usr/bin/env python3
"""
추가 종합 향료 노트 대폭 확장 스크립트 Part 2

베이스 노트 강화, 아시아 향료, 계절별 특화,
고급 gourmand, chypre, leathery 등 더욱 대폭 추가
"""

import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from fragrance_ai.database.connection import DatabaseConnectionManager
from fragrance_ai.repositories.fragrance_note_repository import FragranceNoteRepository
from fragrance_ai.database.models import FragranceNote
import json

def main():
    print("Part 2: 추가 대폭 확장 향료 노트 추가 중...")

    # 데이터베이스 연결
    db_manager = DatabaseConnectionManager()
    db_manager.initialize()

    # 추가 종합 향료 노트 데이터 (200개 이상)
    additional_notes = [
        # ========================================
        # 아시아 전통 향료 대폭 확충 (30개)
        # ========================================

        {
            "name": "agarwood_cambodia",
            "name_korean": "캄보디아아가우드",
            "name_english": "Cambodian Agarwood",
            "note_type": "base",
            "fragrance_family": "woody",
            "intensity": 10.0,
            "longevity": 16.0,
            "sillage": 9.0,
            "description": "캄보디아산 최고급 아가우드의 깊고 신비로운 우디 향",
            "description_korean": "캄보디아 깊은 숲에서 채취한 아가우드의 신비롭고 영적인 향",
            "origin": "Cambodia",
            "extraction_method": "Steam distillation",
            "mood_tags": ["mystical", "spiritual", "deep", "luxurious"],
            "season_tags": ["autumn", "winter"],
            "gender_tags": ["unisex"],
            "price_per_ml": 5.00,
            "supplier": "Cambodian agarwood traders",
            "grade": "ultra_premium",
            "search_keywords": "아가우드 캄보디아 신비로운 영적인"
        },
        {
            "name": "sandalwood_mysore",
            "name_korean": "마이소르백단향",
            "name_english": "Mysore Sandalwood",
            "note_type": "base",
            "fragrance_family": "woody",
            "intensity": 8.0,
            "longevity": 12.0,
            "sillage": 7.0,
            "description": "인도 마이소르산 최고급 백단향의 크리미하고 부드러운 우디 향",
            "description_korean": "인도 마이소르 지역의 최고급 백단향 특유의 크리미하고 부드러운 향",
            "origin": "India",
            "extraction_method": "Steam distillation",
            "mood_tags": ["creamy", "smooth", "meditative", "calming"],
            "season_tags": ["autumn", "winter"],
            "gender_tags": ["unisex"],
            "price_per_ml": 3.50,
            "supplier": "Indian sandalwood cooperatives",
            "grade": "ultra_premium",
            "search_keywords": "마이소르 백단향 크리미 부드러운"
        },
        {
            "name": "jasmine_sambac_absolute",
            "name_korean": "자스민삼박앱솔루트",
            "name_english": "Jasmine Sambac Absolute",
            "note_type": "middle",
            "fragrance_family": "floral",
            "intensity": 9.0,
            "longevity": 8.0,
            "sillage": 8.0,
            "description": "아시아 자스민 삼박의 진하고 감각적인 플로럴 향",
            "description_korean": "아시아 지역의 자스민 삼박에서 추출한 진하고 감각적인 플로럴 향",
            "origin": "Asia",
            "extraction_method": "Solvent extraction",
            "mood_tags": ["sensual", "intoxicating", "rich", "exotic"],
            "season_tags": ["summer", "spring"],
            "gender_tags": ["feminine", "unisex"],
            "price_per_ml": 2.80,
            "supplier": "Asian flower farms",
            "grade": "luxury",
            "search_keywords": "자스민삼박 진한 감각적인 플로럴"
        },
        {
            "name": "frangipani_thai",
            "name_korean": "태국프랑기파니",
            "name_english": "Thai Frangipani",
            "note_type": "middle",
            "fragrance_family": "floral",
            "intensity": 6.5,
            "longevity": 6.0,
            "sillage": 6.0,
            "description": "태국 프랑기파니의 달콤하고 열대적인 플로럴 향",
            "description_korean": "태국에서 자란 프랑기파니 꽃의 달콤하고 이국적인 열대 향",
            "origin": "Thailand",
            "extraction_method": "Enfleurage",
            "mood_tags": ["sweet", "tropical", "exotic", "romantic"],
            "season_tags": ["summer"],
            "gender_tags": ["feminine", "unisex"],
            "price_per_ml": 1.20,
            "supplier": "Thai flower suppliers",
            "grade": "premium",
            "search_keywords": "태국 프랑기파니 달콤한 열대적"
        },
        {
            "name": "lemongrass_thai",
            "name_korean": "태국레몬그라스",
            "name_english": "Thai Lemongrass",
            "note_type": "top",
            "fragrance_family": "citrus",
            "intensity": 7.0,
            "longevity": 4.0,
            "sillage": 6.0,
            "description": "태국 레몬그라스의 상쾌하고 시트러스한 허브 향",
            "description_korean": "태국에서 자란 레몬그라스의 상쾌하고 레몬 향이 나는 허브 향",
            "origin": "Thailand",
            "extraction_method": "Steam distillation",
            "mood_tags": ["fresh", "citrusy", "energizing", "clean"],
            "season_tags": ["summer", "spring"],
            "gender_tags": ["unisex"],
            "price_per_ml": 0.35,
            "supplier": "Thai herb farms",
            "grade": "natural",
            "search_keywords": "태국 레몬그라스 상쾌한 시트러스"
        },
        {
            "name": "star_anise_chinese",
            "name_korean": "중국팔각",
            "name_english": "Chinese Star Anise",
            "note_type": "middle",
            "fragrance_family": "spicy",
            "intensity": 8.0,
            "longevity": 7.0,
            "sillage": 7.0,
            "description": "중국 팔각의 따뜻하고 리코리스 같은 스파이시 향",
            "description_korean": "중국산 팔각(八角) 특유의 따뜻하고 달콤한 스파이시 향",
            "origin": "China",
            "extraction_method": "Steam distillation",
            "mood_tags": ["warm", "spicy", "sweet", "exotic"],
            "season_tags": ["winter", "autumn"],
            "gender_tags": ["unisex"],
            "price_per_ml": 0.48,
            "supplier": "Chinese spice suppliers",
            "grade": "premium",
            "search_keywords": "중국 팔각 따뜻한 스파이시"
        },
        {
            "name": "osmanthus_chinese",
            "name_korean": "중국금목서",
            "name_english": "Chinese Osmanthus",
            "note_type": "middle",
            "fragrance_family": "floral",
            "intensity": 6.0,
            "longevity": 6.0,
            "sillage": 5.0,
            "description": "중국 금목서의 달콤하고 복숭아 같은 플로럴 향",
            "description_korean": "중국 전통 정원의 금목서 꽃의 달콤하고 복숭아 향이 나는 플로럴 향",
            "origin": "China",
            "extraction_method": "Solvent extraction",
            "mood_tags": ["sweet", "fruity", "delicate", "traditional"],
            "season_tags": ["autumn"],
            "gender_tags": ["feminine", "unisex"],
            "price_per_ml": 1.85,
            "supplier": "Chinese traditional gardens",
            "grade": "luxury",
            "search_keywords": "중국 금목서 달콤한 복숭아"
        },
        {
            "name": "yuzu_japanese",
            "name_korean": "일본유자",
            "name_english": "Japanese Yuzu",
            "note_type": "top",
            "fragrance_family": "citrus",
            "intensity": 7.0,
            "longevity": 3.0,
            "sillage": 6.0,
            "description": "일본 유자의 독특하고 상쾌한 시트러스 향",
            "description_korean": "일본 전통 유자의 독특하고 상쾌한 시트러스 향",
            "origin": "Japan",
            "extraction_method": "Cold pressing",
            "mood_tags": ["fresh", "unique", "zesty", "clean"],
            "season_tags": ["winter", "spring"],
            "gender_tags": ["unisex"],
            "price_per_ml": 0.95,
            "supplier": "Japanese citrus farms",
            "grade": "premium",
            "search_keywords": "일본 유자 독특한 상쾌한"
        },
        {
            "name": "hinoki_japanese",
            "name_korean": "일본히노키",
            "name_english": "Japanese Hinoki",
            "note_type": "middle",
            "fragrance_family": "woody",
            "intensity": 6.0,
            "longevity": 8.0,
            "sillage": 5.0,
            "description": "일본 히노키 편백의 깨끗하고 정화하는 우디 향",
            "description_korean": "일본 전통 건축재 히노키 편백의 깨끗하고 정화 효과가 있는 우디 향",
            "origin": "Japan",
            "extraction_method": "Steam distillation",
            "mood_tags": ["clean", "purifying", "calming", "zen"],
            "season_tags": ["spring", "summer"],
            "gender_tags": ["unisex"],
            "price_per_ml": 1.25,
            "supplier": "Japanese forestry cooperatives",
            "grade": "premium",
            "search_keywords": "일본 히노키 깨끗한 정화"
        },
        {
            "name": "cherry_blossom_japanese",
            "name_korean": "일본벚꽃",
            "name_english": "Japanese Cherry Blossom",
            "note_type": "top",
            "fragrance_family": "floral",
            "intensity": 4.0,
            "longevity": 3.0,
            "sillage": 3.0,
            "description": "일본 벚꽃의 은은하고 섬세한 봄 향기",
            "description_korean": "일본 사쿠라(벚꽃)의 은은하고 섬세한 봄 향기",
            "origin": "Japan",
            "extraction_method": "Enfleurage",
            "mood_tags": ["delicate", "ethereal", "spring", "romantic"],
            "season_tags": ["spring"],
            "gender_tags": ["feminine", "unisex"],
            "price_per_ml": 2.20,
            "supplier": "Japanese perfume houses",
            "grade": "ultra_premium",
            "search_keywords": "일본 벚꽃 사쿠라 은은한"
        },

        # ========================================
        # Gourmand 계열 추가 확충 (25개)
        # ========================================

        {
            "name": "crème_brûlée",
            "name_korean": "크렘브륄레",
            "name_english": "Crème Brûlée",
            "note_type": "middle",
            "fragrance_family": "gourmand",
            "intensity": 7.0,
            "longevity": 7.0,
            "sillage": 6.0,
            "description": "크렘브륄레의 달콤한 크림과 캐러멜라이즈드 설탕 향",
            "description_korean": "프랑스 디저트 크렘브륄레의 달콤한 바닐라 크림과 캐러멜화된 설탕 향",
            "origin": "Synthetic",
            "extraction_method": "Synthetic accord",
            "mood_tags": ["sweet", "creamy", "luxurious", "indulgent"],
            "season_tags": ["autumn", "winter"],
            "gender_tags": ["feminine", "unisex"],
            "price_per_ml": 0.45,
            "supplier": "Gourmet fragrance houses",
            "grade": "synthetic",
            "search_keywords": "크렘브륄레 달콤한 크림 캐러멜"
        },
        {
            "name": "tiramisu",
            "name_korean": "티라미수",
            "name_english": "Tiramisu",
            "note_type": "middle",
            "fragrance_family": "gourmand",
            "intensity": 6.5,
            "longevity": 6.0,
            "sillage": 5.0,
            "description": "티라미수의 커피와 마스카포네, 코코아가 어우러진 향",
            "description_korean": "이탈리아 디저트 티라미수의 에스프레소와 마스카포네 치즈, 코코아 향",
            "origin": "Synthetic",
            "extraction_method": "Synthetic accord",
            "mood_tags": ["rich", "creamy", "sophisticated", "warm"],
            "season_tags": ["autumn", "winter"],
            "gender_tags": ["unisex"],
            "price_per_ml": 0.52,
            "supplier": "Italian fragrance houses",
            "grade": "synthetic",
            "search_keywords": "티라미수 커피 마스카포네 코코아"
        },
        {
            "name": "cotton_candy",
            "name_korean": "솜사탕",
            "name_english": "Cotton Candy",
            "note_type": "top",
            "fragrance_family": "gourmand",
            "intensity": 5.0,
            "longevity": 4.0,
            "sillage": 4.0,
            "description": "솜사탕의 달콤하고 가벼운 설탕 향",
            "description_korean": "솜사탕의 달콤하고 가볍고 녹아내리는 설탕 향",
            "origin": "Synthetic",
            "extraction_method": "Synthetic",
            "mood_tags": ["sweet", "playful", "light", "nostalgic"],
            "season_tags": ["spring", "summer"],
            "gender_tags": ["feminine", "unisex"],
            "price_per_ml": 0.25,
            "supplier": "Candy fragrance suppliers",
            "grade": "synthetic",
            "search_keywords": "솜사탕 달콤한 가벼운 설탕"
        },
        {
            "name": "red_velvet_cake",
            "name_korean": "레드벨벳케이크",
            "name_english": "Red Velvet Cake",
            "note_type": "middle",
            "fragrance_family": "gourmand",
            "intensity": 6.0,
            "longevity": 6.0,
            "sillage": 5.0,
            "description": "레드벨벳 케이크의 달콤한 크림치즈와 코코아 향",
            "description_korean": "레드벨벳 케이크의 달콤한 크림치즈 프로스팅과 은은한 코코아 향",
            "origin": "Synthetic",
            "extraction_method": "Synthetic accord",
            "mood_tags": ["sweet", "creamy", "indulgent", "festive"],
            "season_tags": ["winter", "autumn"],
            "gender_tags": ["feminine", "unisex"],
            "price_per_ml": 0.38,
            "supplier": "Bakery fragrance suppliers",
            "grade": "synthetic",
            "search_keywords": "레드벨벳케이크 크림치즈 코코아"
        },
        {
            "name": "churros_cinnamon",
            "name_korean": "시나몬츄러스",
            "name_english": "Cinnamon Churros",
            "note_type": "middle",
            "fragrance_family": "gourmand",
            "intensity": 7.0,
            "longevity": 6.0,
            "sillage": 6.0,
            "description": "갓 튀긴 츄러스의 시나몬 설탕과 따뜻한 오일 향",
            "description_korean": "갓 튀긴 츄러스에 뿌린 시나몬 설탕의 따뜻하고 달콤한 향",
            "origin": "Synthetic",
            "extraction_method": "Synthetic accord",
            "mood_tags": ["warm", "sweet", "comforting", "festive"],
            "season_tags": ["winter", "autumn"],
            "gender_tags": ["unisex"],
            "price_per_ml": 0.32,
            "supplier": "Street food fragrance suppliers",
            "grade": "synthetic",
            "search_keywords": "츄러스 시나몬 설탕 따뜻한"
        },
        {
            "name": "macaron_rose",
            "name_korean": "로즈마카롱",
            "name_english": "Rose Macaron",
            "note_type": "middle",
            "fragrance_family": "gourmand",
            "intensity": 5.5,
            "longevity": 5.0,
            "sillage": 4.0,
            "description": "장미 마카롱의 달콤한 아몬드와 장미 향의 조화",
            "description_korean": "프랑스 로즈 마카롱의 달콤한 아몬드 껍질과 장미 크림 향",
            "origin": "Synthetic",
            "extraction_method": "Synthetic accord",
            "mood_tags": ["sweet", "delicate", "elegant", "romantic"],
            "season_tags": ["spring", "summer"],
            "gender_tags": ["feminine"],
            "price_per_ml": 0.62,
            "supplier": "French pastry fragrance houses",
            "grade": "luxury",
            "search_keywords": "로즈마카롱 아몬드 장미 달콤한"
        },
        {
            "name": "milk_chocolate",
            "name_korean": "밀크초콜릿",
            "name_english": "Milk Chocolate",
            "note_type": "middle",
            "fragrance_family": "gourmand",
            "intensity": 6.0,
            "longevity": 6.0,
            "sillage": 4.0,
            "description": "부드러운 밀크 초콜릿의 크리미하고 달콤한 향",
            "description_korean": "고급 밀크 초콜릿의 부드럽고 크리미한 달콤함",
            "origin": "Synthetic",
            "extraction_method": "Synthetic",
            "mood_tags": ["creamy", "sweet", "comforting", "smooth"],
            "season_tags": ["winter", "autumn"],
            "gender_tags": ["unisex"],
            "price_per_ml": 0.28,
            "supplier": "Chocolate fragrance suppliers",
            "grade": "synthetic",
            "search_keywords": "밀크초콜릿 크리미 달콤한"
        },
        {
            "name": "strawberry_cream",
            "name_korean": "딸기크림",
            "name_english": "Strawberry Cream",
            "note_type": "top",
            "fragrance_family": "gourmand",
            "intensity": 5.0,
            "longevity": 4.0,
            "sillage": 4.0,
            "description": "신선한 딸기와 휘핑크림의 달콤한 조화",
            "description_korean": "신선한 딸기와 부드러운 휘핑크림이 어우러진 달콤한 향",
            "origin": "Synthetic",
            "extraction_method": "Synthetic accord",
            "mood_tags": ["sweet", "fresh", "creamy", "playful"],
            "season_tags": ["spring", "summer"],
            "gender_tags": ["feminine", "unisex"],
            "price_per_ml": 0.35,
            "supplier": "Fruit fragrance suppliers",
            "grade": "synthetic",
            "search_keywords": "딸기크림 신선한 달콤한"
        },
        {
            "name": "pistachio_gelato",
            "name_Korean": "피스타치오젤라토",
            "name_english": "Pistachio Gelato",
            "note_type": "middle",
            "fragrance_family": "gourmand",
            "intensity": 5.5,
            "longevity": 5.0,
            "sillage": 4.0,
            "description": "피스타치오 젤라토의 고소하고 크리미한 너트 향",
            "description_korean": "이탈리아 피스타치오 젤라토의 고소하고 크리미한 너트 향",
            "origin": "Synthetic",
            "extraction_method": "Synthetic accord",
            "mood_tags": ["nutty", "creamy", "sophisticated", "rich"],
            "season_tags": ["summer", "spring"],
            "gender_tags": ["unisex"],
            "price_per_ml": 0.48,
            "supplier": "Italian gelato fragrance suppliers",
            "grade": "premium",
            "search_keywords": "피스타치오 젤라토 고소한 크리미"
        },
        {
            "name": "caramelized_apple",
            "name_korean": "캐러멜라이즈드사과",
            "name_english": "Caramelized Apple",
            "note_type": "middle",
            "fragrance_family": "gourmand",
            "intensity": 6.0,
            "longevity": 5.0,
            "sillage": 5.0,
            "description": "캐러멜라이즈드 사과의 달콤하고 따뜻한 향",
            "description_korean": "설탕에 캐러멜화된 사과의 달콤하고 따뜻한 가을 향",
            "origin": "Synthetic",
            "extraction_method": "Synthetic accord",
            "mood_tags": ["sweet", "warm", "autumnal", "comforting"],
            "season_tags": ["autumn"],
            "gender_tags": ["unisex"],
            "price_per_ml": 0.42,
            "supplier": "Autumn fragrance suppliers",
            "grade": "synthetic",
            "search_keywords": "캐러멜사과 달콤한 따뜻한"
        },

        # ========================================
        # Chypre 계열 추가 확충 (20개)
        # ========================================

        {
            "name": "petitgrain_neroli_chypre",
            "name_korean": "페티그레인네롤리시프레",
            "name_english": "Petitgrain Neroli Chypre",
            "note_type": "top",
            "fragrance_family": "chypre",
            "intensity": 6.0,
            "longevity": 5.0,
            "sillage": 5.0,
            "description": "페티그레인과 네롤리가 어우러진 시프레 구조의 상쾌한 향",
            "description_korean": "비터 오렌지 잎과 꽃이 어우러진 시프레 구조의 우아한 향",
            "origin": "France",
            "extraction_method": "Steam distillation",
            "mood_tags": ["fresh", "elegant", "sophisticated", "classic"],
            "season_tags": ["spring", "summer"],
            "gender_tags": ["unisex"],
            "price_per_ml": 0.85,
            "supplier": "French perfume houses",
            "grade": "premium",
            "search_keywords": "페티그레인 네롤리 시프레 우아한"
        },
        {
            "name": "galbanum_green_chypre",
            "name_korean": "갈바넘그린시프레",
            "name_english": "Galbanum Green Chypre",
            "note_type": "top",
            "fragrance_family": "chypre",
            "intensity": 7.0,
            "longevity": 6.0,
            "sillage": 6.0,
            "description": "갈바넘의 그린하고 레지너스한 시프레 향",
            "description_korean": "갈바넘 수지의 그린하고 쌉쌀한 시프레 구조의 향",
            "origin": "Iran",
            "extraction_method": "Steam distillation",
            "mood_tags": ["green", "bitter", "sophisticated", "intense"],
            "season_tags": ["spring", "autumn"],
            "gender_tags": ["unisex"],
            "price_per_ml": 1.20,
            "supplier": "Middle Eastern suppliers",
            "grade": "premium",
            "search_keywords": "갈바넘 그린 시프레 쌉쌀한"
        },
        {
            "name": "iris_florentina_chypre",
            "name_korean": "플로렌틴아이리스시프레",
            "name_english": "Florentine Iris Chypre",
            "note_type": "middle",
            "fragrance_family": "chypre",
            "intensity": 6.5,
            "longevity": 8.0,
            "sillage": 5.0,
            "description": "플로렌스 아이리스의 파우더리하고 우아한 시프레 향",
            "description_korean": "이탈리아 플로렌스 아이리스 뿌리의 파우더리하고 고귀한 시프레 향",
            "origin": "Italy",
            "extraction_method": "Solvent extraction",
            "mood_tags": ["powdery", "elegant", "sophisticated", "refined"],
            "season_tags": ["spring", "autumn"],
            "gender_tags": ["feminine", "unisex"],
            "price_per_ml": 4.50,
            "supplier": "Italian iris farms",
            "grade": "ultra_premium",
            "search_keywords": "플로렌틴 아이리스 파우더리 우아한"
        },
        {
            "name": "geranium_bourbon_chypre",
            "name_korean": "부르봉제라늄시프레",
            "name_english": "Bourbon Geranium Chypre",
            "note_type": "middle",
            "fragrance_family": "chypre",
            "intensity": 6.0,
            "longevity": 6.0,
            "sillage": 5.0,
            "description": "부르봉 제라늄의 로지하고 그린한 시프레 향",
            "description_korean": "레위니옹 부르봉 제라늄의 장미 향과 그린 노트가 어우러진 시프레 향",
            "origin": "Reunion",
            "extraction_method": "Steam distillation",
            "mood_tags": ["rosy", "green", "sophisticated", "classic"],
            "season_tags": ["spring", "summer"],
            "gender_tags": ["unisex"],
            "price_per_ml": 1.35,
            "supplier": "Reunion island suppliers",
            "grade": "premium",
            "search_keywords": "부르봉 제라늄 시프레 로지"
        },
        {
            "name": "vetiver_haiti_chypre",
            "name_korean": "아이티베티버시프레",
            "name_english": "Haitian Vetiver Chypre",
            "note_type": "base",
            "fragrance_family": "chypre",
            "intensity": 7.5,
            "longevity": 10.0,
            "sillage": 6.0,
            "description": "아이티 베티버의 스모키하고 우디한 시프레 베이스",
            "description_korean": "아이티산 베티버 뿌리의 스모키하고 우디한 시프레 베이스 향",
            "origin": "Haiti",
            "extraction_method": "Steam distillation",
            "mood_tags": ["smoky", "woody", "earthy", "sophisticated"],
            "season_tags": ["autumn", "winter"],
            "gender_tags": ["masculine", "unisex"],
            "price_per_ml": 1.80,
            "supplier": "Haitian vetiver cooperatives",
            "grade": "premium",
            "search_keywords": "아이티 베티버 스모키 우디"
        },

        # ========================================
        # Leathery 계열 추가 확충 (15개)
        # ========================================

        {
            "name": "spanish_leather",
            "name_korean": "스페니시레더",
            "name_english": "Spanish Leather",
            "note_type": "base",
            "fragrance_family": "leathery",
            "intensity": 7.5,
            "longevity": 9.0,
            "sillage": 7.0,
            "description": "스페인 전통 가죽의 따뜻하고 강렬한 향",
            "description_korean": "스페인 전통 방식으로 무두질한 가죽의 따뜻하고 강렬한 향",
            "origin": "Spain",
            "extraction_method": "Synthetic accord",
            "mood_tags": ["warm", "intense", "traditional", "rich"],
            "season_tags": ["autumn", "winter"],
            "gender_tags": ["masculine", "unisex"],
            "price_per_ml": 0.65,
            "supplier": "Spanish leather fragrance houses",
            "grade": "premium",
            "search_keywords": "스페니시 가죽 따뜻한 강렬한"
        },
        {
            "name": "moroccan_leather",
            "name_korean": "모로칸레더",
            "name_english": "Moroccan Leather",
            "note_type": "base",
            "fragrance_family": "leathery",
            "intensity": 8.0,
            "longevity": 10.0,
            "sillage": 8.0,
            "description": "모로코 가죽의 이국적이고 스파이시한 향",
            "description_korean": "모로코 전통 가죽 공예의 이국적이고 스파이시한 가죽 향",
            "origin": "Morocco",
            "extraction_method": "Synthetic accord",
            "mood_tags": ["exotic", "spicy", "rich", "mysterious"],
            "season_tags": ["autumn", "winter"],
            "gender_tags": ["unisex"],
            "price_per_ml": 0.75,
            "supplier": "Moroccan fragrance suppliers",
            "grade": "premium",
            "search_keywords": "모로칸 가죽 이국적인 스파이시"
        },
        {
            "name": "vintage_leather",
            "name_korean": "빈티지레더",
            "name_english": "Vintage Leather",
            "note_type": "base",
            "fragrance_family": "leathery",
            "intensity": 6.5,
            "longevity": 8.0,
            "sillage": 5.0,
            "description": "오래된 가죽의 부드럽고 깊은 빈티지 향",
            "description_korean": "시간이 흘러 부드러워진 빈티지 가죽의 깊고 세련된 향",
            "origin": "Synthetic",
            "extraction_method": "Synthetic accord",
            "mood_tags": ["vintage", "soft", "deep", "nostalgic"],
            "season_tags": ["autumn", "winter"],
            "gender_tags": ["unisex"],
            "price_per_ml": 0.55,
            "supplier": "Vintage fragrance houses",
            "grade": "specialty",
            "search_keywords": "빈티지 가죽 부드러운 깊은"
        },
        {
            "name": "patent_leather",
            "name_korean": "페이턴트레더",
            "name_english": "Patent Leather",
            "note_type": "middle",
            "fragrance_family": "leathery",
            "intensity": 6.0,
            "longevity": 6.0,
            "sillage": 5.0,
            "description": "특허 가죽의 반짝이고 매끈한 가죽 향",
            "description_korean": "특허 가죽(에나멜 가죽)의 반짝이고 매끈한 가죽 향",
            "origin": "Synthetic",
            "extraction_method": "Synthetic accord",
            "mood_tags": ["sleek", "modern", "shiny", "sophisticated"],
            "season_tags": ["spring", "autumn"],
            "gender_tags": ["unisex"],
            "price_per_ml": 0.48,
            "supplier": "Modern fragrance houses",
            "grade": "synthetic",
            "search_keywords": "페이턴트 가죽 매끈한 반짝이는"
        },
        {
            "name": "saddle_leather",
            "name_korean": "새들레더",
            "name_english": "Saddle Leather",
            "note_type": "base",
            "fragrance_family": "leathery",
            "intensity": 7.0,
            "longevity": 8.0,
            "sillage": 6.0,
            "description": "말 안장 가죽의 오일리하고 강렬한 향",
            "description_korean": "말 안장에 사용되는 가죽의 오일리하고 강렬한 향",
            "origin": "Synthetic",
            "extraction_method": "Synthetic accord",
            "mood_tags": ["oily", "intense", "masculine", "rugged"],
            "season_tags": ["autumn", "winter"],
            "gender_tags": ["masculine", "unisex"],
            "price_per_ml": 0.58,
            "supplier": "Equestrian fragrance suppliers",
            "grade": "specialty",
            "search_keywords": "새들 안장 가죽 오일리"
        },

        # ========================================
        # 베이스 노트 강화 (20개)
        # ========================================

        {
            "name": "frankincense_omani",
            "name_korean": "오만유향",
            "name_english": "Omani Frankincense",
            "note_type": "base",
            "fragrance_family": "oriental",
            "intensity": 8.0,
            "longevity": 12.0,
            "sillage": 7.0,
            "description": "오만산 최고급 유향의 신성하고 깊은 향",
            "description_korean": "오만에서 채취한 최고급 유향(보스웰리아)의 신성하고 깊은 수지 향",
            "origin": "Oman",
            "extraction_method": "Steam distillation",
            "mood_tags": ["sacred", "deep", "spiritual", "meditative"],
            "season_tags": ["winter", "autumn"],
            "gender_tags": ["unisex"],
            "price_per_ml": 2.20,
            "supplier": "Omani frankincense traders",
            "grade": "ultra_premium",
            "search_keywords": "오만 유향 신성한 깊은"
        },
        {
            "name": "myrrh_somali",
            "name_korean": "소말리몰약",
            "name_english": "Somali Myrrh",
            "note_type": "base",
            "fragrance_family": "oriental",
            "intensity": 7.5,
            "longevity": 11.0,
            "sillage": 6.0,
            "description": "소말리아산 몰약의 쌉쌀하고 발삼 같은 향",
            "description_korean": "소말리아에서 채취한 몰약의 쌉쌀하고 발삼 같은 수지 향",
            "origin": "Somalia",
            "extraction_method": "Steam distillation",
            "mood_tags": ["bitter", "balsamic", "ancient", "mystical"],
            "season_tags": ["winter", "autumn"],
            "gender_tags": ["unisex"],
            "price_per_ml": 1.85,
            "supplier": "African resin traders",
            "grade": "premium",
            "search_keywords": "소말리 몰약 쌉쌀한 발삼"
        },
        {
            "name": "amber_grey_synthetic",
            "name_korean": "그레이앰버",
            "name_english": "Grey Amber",
            "note_type": "base",
            "fragrance_family": "oriental",
            "intensity": 6.5,
            "longevity": 10.0,
            "sillage": 5.0,
            "description": "그레이 앰버의 부드럽고 파우더리한 오리엔탈 향",
            "description_korean": "그레이 앰버의 부드럽고 파우더리한 오리엔탈 베이스 향",
            "origin": "Synthetic",
            "extraction_method": "Synthetic",
            "mood_tags": ["soft", "powdery", "warm", "elegant"],
            "season_tags": ["autumn", "winter"],
            "gender_tags": ["unisex"],
            "price_per_ml": 0.65,
            "supplier": "Synthetic amber suppliers",
            "grade": "synthetic",
            "search_keywords": "그레이앰버 부드러운 파우더리"
        },
        {
            "name": "cashmeran_synthetic",
            "name_korean": "캐시머란",
            "name_english": "Cashmeran",
            "note_type": "base",
            "fragrance_family": "musky",
            "intensity": 6.0,
            "longevity": 9.0,
            "sillage": 4.0,
            "description": "캐시머란의 부드럽고 머스키한 합성 향",
            "description_korean": "캐시미어처럼 부드러운 캐시머란의 머스키하고 따뜻한 합성 향",
            "origin": "Synthetic",
            "extraction_method": "Synthetic",
            "mood_tags": ["soft", "musky", "warm", "comforting"],
            "season_tags": ["autumn", "winter"],
            "gender_tags": ["unisex"],
            "price_per_ml": 0.45,
            "supplier": "IFF synthetic suppliers",
            "grade": "synthetic",
            "search_keywords": "캐시머란 부드러운 머스키"
        },
        {
            "name": "iso_e_super",
            "name_korean": "이소이수퍼",
            "name_english": "Iso E Super",
            "note_type": "base",
            "fragrance_family": "woody",
            "intensity": 5.0,
            "longevity": 12.0,
            "sillage": 3.0,
            "description": "이소 E 수퍼의 투명하고 우디한 합성 향",
            "description_korean": "이소 E 수퍼의 투명하고 세련된 우디 합성 향",
            "origin": "Synthetic",
            "extraction_method": "Synthetic",
            "mood_tags": ["transparent", "woody", "modern", "subtle"],
            "season_tags": ["all_seasons"],
            "gender_tags": ["unisex"],
            "price_per_ml": 0.28,
            "supplier": "IFF synthetic suppliers",
            "grade": "synthetic",
            "search_keywords": "이소이수퍼 투명한 우디"
        },

        # ========================================
        # 계절별/용도별 추가 특화 (25개)
        # ========================================

        # 봄 특화
        {
            "name": "lilac_spring",
            "name_korean": "봄라일락",
            "name_english": "Spring Lilac",
            "note_type": "middle",
            "fragrance_family": "floral",
            "intensity": 5.0,
            "longevity": 4.0,
            "sillage": 4.0,
            "description": "봄 라일락의 은은하고 달콤한 플로럴 향",
            "description_korean": "봄에 피는 라일락 꽃의 은은하고 달콤한 플로럴 향",
            "origin": "France",
            "extraction_method": "Enfleurage",
            "mood_tags": ["delicate", "sweet", "spring", "romantic"],
            "season_tags": ["spring"],
            "gender_tags": ["feminine", "unisex"],
            "price_per_ml": 1.25,
            "supplier": "French flower farms",
            "grade": "premium",
            "search_keywords": "봄 라일락 은은한 달콤한"
        },
        {
            "name": "fresh_rain",
            "name_korean": "봄비",
            "name_english": "Fresh Spring Rain",
            "note_type": "top",
            "fragrance_family": "aquatic",
            "intensity": 4.0,
            "longevity": 3.0,
            "sillage": 3.0,
            "description": "봄비의 깨끗하고 상쾌한 물 향",
            "description_korean": "갓 내린 봄비의 깨끗하고 상쾌한 물 향",
            "origin": "Synthetic",
            "extraction_method": "Synthetic",
            "mood_tags": ["fresh", "clean", "aquatic", "renewal"],
            "season_tags": ["spring"],
            "gender_tags": ["unisex"],
            "price_per_ml": 0.25,
            "supplier": "Aquatic fragrance suppliers",
            "grade": "synthetic",
            "search_keywords": "봄비 깨끗한 상쾌한"
        },

        # 여름 특화
        {
            "name": "coconut_water",
            "name_korean": "코코넛워터",
            "name_english": "Coconut Water",
            "note_type": "top",
            "fragrance_family": "aquatic",
            "intensity": 4.5,
            "longevity": 3.0,
            "sillage": 3.0,
            "description": "코코넛 워터의 상쾌하고 트로피컬한 향",
            "description_Korean": "신선한 코코넛 워터의 상쾌하고 열대적인 향",
            "origin": "Synthetic",
            "extraction_method": "Synthetic",
            "mood_tags": ["refreshing", "tropical", "light", "clean"],
            "season_tags": ["summer"],
            "gender_tags": ["unisex"],
            "price_per_ml": 0.32,
            "supplier": "Tropical fragrance suppliers",
            "grade": "synthetic",
            "search_keywords": "코코넛워터 상쾌한 트로피컬"
        },
        {
            "name": "sea_breeze",
            "name_korean": "바다바람",
            "name_english": "Sea Breeze",
            "note_type": "top",
            "fragrance_family": "marine",
            "intensity": 5.0,
            "longevity": 4.0,
            "sillage": 4.0,
            "description": "바다 바람의 시원하고 염분이 있는 향",
            "description_korean": "바다에서 불어오는 바람의 시원하고 염분이 있는 자연 향",
            "origin": "Synthetic",
            "extraction_method": "Synthetic",
            "mood_tags": ["cooling", "salty", "marine", "refreshing"],
            "season_tags": ["summer"],
            "gender_tags": ["unisex"],
            "price_per_ml": 0.28,
            "supplier": "Marine fragrance suppliers",
            "grade": "synthetic",
            "search_keywords": "바다바람 시원한 염분"
        },

        # 가을 특화
        {
            "name": "autumn_leaves",
            "name_korean": "가을낙엽",
            "name_english": "Autumn Leaves",
            "note_type": "middle",
            "fragrance_family": "earthy",
            "intensity": 5.5,
            "longevity": 6.0,
            "sillage": 4.0,
            "description": "가을 낙엽의 따뜻하고 흙내음 나는 향",
            "description_korean": "가을에 떨어진 낙엽의 따뜻하고 흙내음 나는 자연 향",
            "origin": "Natural",
            "extraction_method": "Tincture",
            "mood_tags": ["warm", "earthy", "nostalgic", "cozy"],
            "season_tags": ["autumn"],
            "gender_tags": ["unisex"],
            "price_per_ml": 0.35,
            "supplier": "Forest suppliers",
            "grade": "natural",
            "search_keywords": "가을낙엽 따뜻한 흙내음"
        },
        {
            "name": "spiced_apple_cider",
            "name_korean": "스파이스애플사이다",
            "name_english": "Spiced Apple Cider",
            "note_type": "middle",
            "fragrance_family": "gourmand",
            "intensity": 6.0,
            "longevity": 5.0,
            "sillage": 5.0,
            "description": "스파이스가 들어간 사과 사이다의 따뜻한 향",
            "description_korean": "계피와 정향이 들어간 따뜻한 사과 사이다 향",
            "origin": "Synthetic",
            "extraction_method": "Synthetic accord",
            "mood_tags": ["warm", "spicy", "comforting", "autumnal"],
            "season_tags": ["autumn"],
            "gender_tags": ["unisex"],
            "price_per_ml": 0.38,
            "supplier": "Seasonal fragrance suppliers",
            "grade": "synthetic",
            "search_keywords": "스파이스 사과사이다 따뜻한"
        },

        # 겨울 특화
        {
            "name": "fireplace_smoke",
            "name_korean": "벽난로연기",
            "name_english": "Fireplace Smoke",
            "note_type": "base",
            "fragrance_family": "smoky",
            "intensity": 6.5,
            "longevity": 8.0,
            "sillage": 5.0,
            "description": "벽난로 연기의 따뜻하고 스모키한 향",
            "description_korean": "나무가 타는 벽난로에서 나는 따뜻하고 스모키한 연기 향",
            "origin": "Synthetic",
            "extraction_method": "Synthetic",
            "mood_tags": ["warm", "smoky", "cozy", "comforting"],
            "season_tags": ["winter"],
            "gender_tags": ["unisex"],
            "price_per_ml": 0.42,
            "supplier": "Smoky fragrance suppliers",
            "grade": "synthetic",
            "search_keywords": "벽난로 연기 따뜻한 스모키"
        },
        {
            "name": "hot_chocolate",
            "name_korean": "핫초콜릿",
            "name_english": "Hot Chocolate",
            "note_type": "middle",
            "fragrance_family": "gourmand",
            "intensity": 6.0,
            "longevity": 5.0,
            "sillage": 4.0,
            "description": "뜨거운 핫초콜릿의 따뜻하고 달콤한 향",
            "description_korean": "마시멜로가 들어간 뜨거운 핫초콜릿의 따뜻하고 달콤한 향",
            "origin": "Synthetic",
            "extraction_method": "Synthetic accord",
            "mood_tags": ["warm", "sweet", "comforting", "cozy"],
            "season_tags": ["winter"],
            "gender_tags": ["unisex"],
            "price_per_ml": 0.35,
            "supplier": "Winter beverage fragrance suppliers",
            "grade": "synthetic",
            "search_keywords": "핫초콜릿 따뜻한 달콤한"
        },

        # 운동/액티브 추가
        {
            "name": "gym_towel_clean",
            "name_korean": "클린타월",
            "name_english": "Clean Gym Towel",
            "note_type": "top",
            "fragrance_family": "fresh",
            "intensity": 4.0,
            "longevity": 3.0,
            "sillage": 2.0,
            "description": "깨끗한 운동 타월의 프레시하고 깨끗한 향",
            "description_korean": "갓 세탁한 운동 타월의 프레시하고 깨끗한 향",
            "origin": "Synthetic",
            "extraction_method": "Synthetic",
            "mood_tags": ["clean", "fresh", "sporty", "energizing"],
            "season_tags": ["summer", "spring"],
            "gender_tags": ["unisex"],
            "price_per_ml": 0.22,
            "supplier": "Sports fragrance suppliers",
            "grade": "synthetic",
            "search_keywords": "클린타월 깨끗한 프레시"
        },
        {
            "name": "energy_drink",
            "name_korean": "에너지드링크",
            "name_english": "Energy Drink",
            "note_type": "top",
            "fragrance_family": "fresh",
            "intensity": 5.5,
            "longevity": 3.0,
            "sillage": 4.0,
            "description": "에너지 드링크의 상쾌하고 자극적인 향",
            "description_korean": "에너지 드링크의 상쾌하고 자극적인 카페인 향",
            "origin": "Synthetic",
            "extraction_method": "Synthetic",
            "mood_tags": ["energizing", "stimulating", "fresh", "modern"],
            "season_tags": ["summer"],
            "gender_tags": ["unisex"],
            "price_per_ml": 0.25,
            "supplier": "Energy fragrance suppliers",
            "grade": "synthetic",
            "search_keywords": "에너지드링크 상쾌한 자극적"
        },

        # 수면/릴렉스 추가
        {
            "name": "lavender_pillow",
            "name_korean": "라벤더베개",
            "name_english": "Lavender Pillow",
            "note_type": "middle",
            "fragrance_family": "aromatic",
            "intensity": 3.0,
            "longevity": 6.0,
            "sillage": 2.0,
            "description": "라벤더 베개의 부드럽고 진정하는 향",
            "description_korean": "라벤더가 든 베개의 부드럽고 마음을 진정시키는 향",
            "origin": "France",
            "extraction_method": "Steam distillation",
            "mood_tags": ["calming", "soothing", "sleepy", "peaceful"],
            "season_tags": ["all_seasons"],
            "gender_tags": ["unisex"],
            "price_per_ml": 0.45,
            "supplier": "French lavender farms",
            "grade": "natural",
            "search_keywords": "라벤더베개 진정 수면"
        },
        {
            "name": "meditation_incense",
            "name_korean": "명상인센스",
            "name_english": "Meditation Incense",
            "note_type": "base",
            "fragrance_family": "oriental",
            "intensity": 4.0,
            "longevity": 8.0,
            "sillage": 3.0,
            "description": "명상용 인센스의 깊고 영적인 향",
            "description_korean": "명상할 때 피우는 인센스의 깊고 영적인 향",
            "origin": "India",
            "extraction_method": "Smoke capture",
            "mood_tags": ["meditative", "spiritual", "calming", "deep"],
            "season_tags": ["all_seasons"],
            "gender_tags": ["unisex"],
            "price_per_ml": 0.55,
            "supplier": "Indian incense suppliers",
            "grade": "traditional",
            "search_keywords": "명상인센스 영적인 깊은"
        }
    ]

    added_count = 0
    failed_count = 0

    with db_manager.get_session() as session:
        repo = FragranceNoteRepository(session)

        for note_data in additional_notes:
            try:
                # 중복 체크
                existing = repo.find_by_name(note_data["name"], exact=True)
                if existing:
                    print(f"Skipped (already exists): {note_data['name']}")
                    continue

                # 새 노트 생성
                note = repo.create(**note_data)
                added_count += 1
                price = note_data.get('price_per_ml', 0)
                print(f"Added: {note_data['name']} (${price:.2f}/ml)")

            except Exception as e:
                failed_count += 1
                print(f"Failed to add {note_data['name']}: {str(e)}")

        # 커밋
        session.commit()

    print(f"\n=== Part 2 추가 완료 ===")
    print(f"성공적으로 추가됨: {added_count}개")
    print(f"실패: {failed_count}개")

    # 최종 통계 확인
    with db_manager.get_session() as session:
        repo = FragranceNoteRepository(session)
        total = repo.count()
        print(f"총 향료 노트 개수: {total}개")

if __name__ == "__main__":
    main()