name: Reusable Python Setup

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: false
        type: string
        default: '3.10'
      requirements-file:
        description: 'Path to requirements file'
        required: false
        type: string
        default: 'requirements.txt'
      additional-packages:
        description: 'Additional pip packages to install'
        required: false
        type: string
        default: ''

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          if [ -f "${{ inputs.requirements-file }}" ]; then
            pip install -r ${{ inputs.requirements-file }}
          fi

      - name: Install additional packages
        if: inputs.additional-packages != ''
        run: pip install ${{ inputs.additional-packages }}

      - name: Verify installation
        run: |
          python --version
          pip --version
          pip list